# Generated by Django 6.0.1 on 2026-01-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shreyash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='teach_stack',
            new_name='tech_stack',
        ),
    ]
