# Generated by Django 6.0.1 on 2026-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shreyash', '0002_rename_link_project_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='video_path',
            field=models.CharField(blank=True, help_text="Path relative to static folder (e.g. 'videos/demo.mp4')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_path',
            field=models.CharField(blank=True, help_text="Path relative to static folder (e.g. 'skills/python.png')", max_length=200, null=True),
        ),
    ]
